import type { UserProfile } from "@/types/user";
import type { HealthCheckup, DailyLog } from "@/types/health";
import type { Challenge } from "@/types/challenge";
import type { AvatarItem, PointTransaction, RewardBadge } from "@/types/reward";

export const sampleUser: UserProfile = {
  id: "user-001",
  name: "김영희",
  birthYear: 1978,
  gender: "female",
  avatarStyle: "3d",
};

export const sampleCheckup: HealthCheckup = {
  id: "checkup-001",
  checkupDate: "2026-06-01",
  height: 170,
  weight: 72.4,
  bmi: 24.1,
  waist: 86,
  systolicBp: 118,
  diastolicBp: 76,
  fastingGlucose: 98,
  totalCholesterol: 198,
  hdl: 54,
  ldl: 122,
  triglyceride: 145,
  ast: 28,
  alt: 24,
  gammaGtp: 42,
  smokingStatus: "none",
  drinkingFrequency: "low",
  exerciseFrequency: "medium",
};

export const sampleDailyLog: DailyLog = {
  id: "daily-001",
  logDate: "2026-06-22",
  steps: 7842,
  sleepHours: 7.2,
  waterCups: 6,
  mealsCount: 3,
  medicationTaken: true,
  exerciseDone: true,
  conditionScore: 82,
};

export const sampleChallenges: Challenge[] = [
  {
    id: "challenge-001",
    title: "7일 연속 물 6잔 마시기",
    description: "하루 6잔 이상 물 마시기를 실천해보세요.",
    targetType: "water",
    targetValue: 6,
    currentValue: 5,
    startDate: "2026-06-22",
    endDate: "2026-06-28",
    status: "active",
    rewardPoints: 100,
    isRewardClaimed: false,
  },
  {
    id: "challenge-002",
    title: "주 5일 7,000보 걷기",
    description: "무리하지 않고 꾸준히 걷는 습관을 만들어보세요.",
    targetType: "steps",
    targetValue: 7000,
    currentValue: 7842,
    startDate: "2026-06-22",
    endDate: "2026-06-28",
    status: "active",
    rewardPoints: 120,
    isRewardClaimed: false,
  },
  {
    id: "challenge-003",
    title: "수면 7시간 유지하기",
    description: "충분한 수면은 건강한 생활 리듬에 도움이 됩니다.",
    targetType: "sleep",
    targetValue: 7,
    currentValue: 7.2,
    startDate: "2026-06-22",
    endDate: "2026-06-28",
    status: "active",
    rewardPoints: 100,
    isRewardClaimed: false,
  },
  {
    id: "challenge-004",
    title: "식후 10분 걷기",
    description: "식사 후 가볍게 10분 걷는 습관을 함께 만들어보세요.",
    targetType: "exercise",
    targetValue: 1,
    currentValue: 0,
    startDate: "2026-06-22",
    endDate: "2026-06-28",
    status: "active",
    rewardPoints: 100,
    isRewardClaimed: false,
  },
  {
    id: "challenge-005",
    title: "야식 줄이기 챌린지",
    description: "저녁 9시 이후 음식 섭취를 줄여보세요.",
    targetType: "meal",
    targetValue: 3,
    currentValue: 3,
    startDate: "2026-06-22",
    endDate: "2026-06-28",
    status: "active",
    rewardPoints: 100,
    isRewardClaimed: false,
  },
  {
    id: "challenge-006",
    title: "7일 식단 사진 기록 챌린지",
    description: "매일 한 끼 이상 식단 사진을 기록하며 함께 완주해보세요.",
    targetType: "meal",
    targetValue: 7,
    currentValue: 2,
    startDate: "2026-06-22",
    endDate: "2026-06-28",
    status: "active",
    rewardPoints: 100,
    isRewardClaimed: false,
  },
];

export const samplePointTransactions: PointTransaction[] = [
  {
    id: "point-001",
    userId: "user-001",
    type: "earn",
    amount: 50,
    reason: "건강검진 결과 입력",
    createdAt: "2026-06-22T09:00:00",
  },
  {
    id: "point-002",
    userId: "user-001",
    type: "earn",
    amount: 20,
    reason: "AI 건강 리포트 확인",
    createdAt: "2026-06-22T09:10:00",
  },
  {
    id: "point-003",
    userId: "user-001",
    type: "earn",
    amount: 20,
    reason: "7,000보 이상 걷기 달성",
    createdAt: "2026-06-22T18:00:00",
  },
];

export const sampleAvatarItems: AvatarItem[] = [
  {
    id: "item-001",
    name: "산책 운동화",
    category: "accessory",
    price: 300,
    description: "걷기 챌린지에 어울리는 건강한 운동화 아이템입니다.",
    isOwned: false,
    isEquipped: false,
  },
  {
    id: "item-002",
    name: "건강 물병",
    category: "accessory",
    price: 300,
    description: "물 마시기 습관을 응원하는 물병 아이템입니다.",
    isOwned: false,
    isEquipped: false,
  },
  {
    id: "item-003",
    name: "공원 배경",
    category: "background",
    price: 500,
    description: "아바타 배경을 상쾌한 공원 분위기로 바꿉니다.",
    isOwned: false,
    isEquipped: false,
  },
  {
    id: "item-004",
    name: "산책복 의상",
    category: "outfit",
    price: 700,
    description: "건강한 산책 습관을 표현하는 의상입니다.",
    isOwned: false,
    isEquipped: false,
  },
  {
    id: "item-005",
    name: "감성 민트 테마",
    category: "background",
    price: 1000,
    description: "부드러운 민트 컬러의 감성 테마입니다.",
    isOwned: false,
    isEquipped: false,
  },
  {
    id: "item-006",
    name: "프리미엄 3D 아바타 스타일",
    category: "style",
    price: 2000,
    description: "더 풍부한 표정과 움직임을 가진 3D 아바타 스타일입니다.",
    isOwned: false,
    isEquipped: false,
  },
];

export const sampleRewardBadges: RewardBadge[] = [
  {
    id: "badge-001",
    title: "첫 검진 입력",
    description: "건강검진 결과를 처음으로 입력했습니다.",
    condition: "건강검진 결과 1회 입력",
    earnedAt: "2026-06-22T09:00:00",
  },
  {
    id: "badge-002",
    title: "첫 리포트 확인",
    description: "AI 건강 리포트를 처음 확인했습니다.",
    condition: "AI 건강 리포트 1회 확인",
    earnedAt: "2026-06-22T09:10:00",
  },
  {
    id: "badge-003",
    title: "걷기 실천러",
    description: "7,000보 이상 걷기를 달성했습니다.",
    condition: "하루 7,000보 이상 달성",
  },
  {
    id: "badge-004",
    title: "물 마시기 성공",
    description: "하루 물 6잔 마시기를 달성했습니다.",
    condition: "하루 물 6잔 이상 달성",
  },
  {
    id: "badge-005",
    title: "7일 기록 완주",
    description: "7일 연속 생활습관을 기록했습니다.",
    condition: "7일 연속 생활습관 기록",
  },
  {
    id: "badge-006",
    title: "건강습관 시작",
    description: "첫 번째 생활습관 기록을 완료했습니다.",
    condition: "생활습관 기록 1회 완료",
  },
];
